name: 2. Send Clock-Out Notification

on:
  schedule:
    # 🚨 เวลาไทย (UTC+7) 18:00 น. = 11:00 น. ของ UTC
    # (18 โมง - 7 ชั่วโมง = 11 โมง)
    - cron: '0 11 * * *' # 0 นาที, ชั่วโมงที่ 11 (11 โมง UTC)

  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check out code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run Python script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          # รันสคริปต์ พร้อมส่งคำว่า "clock_out" เข้าไป
          python send_notify.py "clock_out"
