name: 1. Send Clock-In Notification

on:
  schedule:
    # 🚨 สำคัญ: เวลาใน GitHub เป็นเวลาสากล (UTC)
    # เวลาไทย (UTC+7) 08:55 น. = 01:55 น. ของ UTC
    # (8 โมงเช้า - 7 ชั่วโมง = ตี 1)
    # ตั้งค่า "นาที ชั่วโมง วัน เดือน วันของสัปดาห์"
    - cron: '55 1 * * *' # 55 นาที, ชั่วโมงที่ 1 (ตี 1 UTC)

  # บรรทัดนี้เอาไว้ให้เรากด "ทดสอบ" เองได้
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest # ยืมใช้คอมพิวเตอร์ Ubuntu (Linux)
    steps:
      - name: 1. Check out code
        uses: actions/checkout@v3 # ดึงโค้ดจาก "บ้าน" (Repo)

      - name: 2. Set up Python
        uses: actions/setup-python@v4 # ติดตั้ง Python
        with:
          python-version: '3.10' # ระบุเวอร์ชัน

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # ติดตั้ง line-bot-sdk

      - name: 4. Run Python script
        env:
          # ดึงกุญแจจาก "ตู้เซฟ" มาใส่ใน Environment
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          # รันสคริปต์ พร้อมส่งคำว่า "clock_in" เข้าไป
          python send_notify.py "clock_in"
