name: ⏱ Clock-In Test (Every 5 minutes)

on:
  schedule:
    # รันทุก 5 นาที เพื่อทดสอบว่า GitHub schedule ทำงานจริงไหม
    - cron: '*/5 * * * *'

  # ให้เรากดทดสอบเองได้ด้วย
  workflow_dispatch:

jobs:
  send_test_message:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Run Python script (test)
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          echo "🔔 Test Clock-In Workflow Triggered at $(date)"
          python send_notify.py "test_clock_in"
